---
title: "Analysis Descriptives"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
editor_options: 
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
options(scipen=9999) # desactivar notacion cientifica
```


```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(theme_bw())
ggplot2::theme_update(text=element_text(size=15,  family="serif"))  
```


# Descriptive

```{r ineq-attitudes}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,sjmisc,GGally,ggplot2)
load(here::here("input/data/proc/study1.RData"))
  # Declare ggplot2 features
ggplot2::theme_set(
  ggplot2::theme(
    panel.background = ggplot2::element_rect(fill = "gray85",
                                             colour = "gray85"),
    panel.border = ggplot2::element_blank(),
    axis.text.y = ggplot2::element_text(size = 13,
                                        hjust = 1),
    title = ggplot2::element_text(size = 13,
                                  face = "bold"),
    legend.text = ggplot2::element_text(size = 12),
    plot.caption = ggplot2::element_text(size = 10,
                                         face = "plain",
                                         hjust = 1)
  )
)

df1 %>%
    dplyr::select(perineq,prefineq,pertransfer,redist) %>%
    na.omit() %>% 
    sjPlot::plot_likert(geom.colors = "PuBu",
                        grid.range  =  c (1.2 , 1),
                        # title = "a. Perception meritocratic",
                          geom.size = c(0.62),
                          catcount = 4,
                          expand.grid = T,
                          values  =  "sum.outside",
                          reverse.colors = T,
                          reverse.scale = T,
                          show.n = FALSE,cat.neutral = 3,
                        show.prc.sign = T,
                        title = '') +
    ggplot2::theme(legend.position = "bottom")

ggsave(plot = last_plot(),filename = "ineq-attitudes.png",device = "png",
       path = here::here("output"),width = 2,height = 1,units = "cm",scale = 15)
```

```{r redist-index}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,
               sjlabelled,haven,stringr,ordinal,texreg,likert)  
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,prefineq,
  class3,
  homclass,
  Q03pcm,
  edyears,
  female,
  agenum,
  union,
  workst,
  WEIGHT,
  region,
  "gini_disp",
  "gini_mkt",
  d10d1,
  rgdpna,
  oecd,
  country2, country
) %>%
  mutate(logrgdpna = log(rgdpna),
         edyears2 = edyears ^ 2,
         age2 = agenum ^ 2) %>%
  filter(country2 != "SVN") %>%
  na.omit()

labels <- get_labels(dfreg$redist)

# polycor::hetcor(data = dfreg$redist,dfreg$prefineq)

dfreg$redist <- factor(dfreg$redist,levels = 1:5,labels = labels)
set_label(dfreg$redist) <- "(B) It is the responsibility of the government to reduce the differences in income between people with high incomes and those with low incomes."

dfreg$prefineq <- factor(dfreg$prefineq,levels = 1:5,labels = labels)
set_label(dfreg$prefineq) <- "(A) For a society to be fair, differences in people’s standard of living should be small."

set1 <- c("#5586B4","#D30132","#999999","#004481","#1C2747")

# sjlabelled::set_label(df2) <- paste0(varlab, " (n = ",summarise_all(df2,~ sum(!is.na(.))),")")

as.data.frame(dfreg) %>%
  dplyr::select(prefineq, redist) %>%
  setNames(get_label(.)) %>%
  likert() %>%
plot(
  low.color = "#D30132",
  high.color = '#5586B4',
  center = 3,
  wrap = 50,
  # plot.percents = TRUE,
  text.size = 3,
) +
  labs(title = "Redistributive preferences",caption = "r = 0.61")

ggsave(plot = last_plot(),filename = "redist_index.png",device = "png",
       path = here::here("output/images"),width = 1.7,height = 0.55,units = "cm",scale = 18)

```


```{r n-ties}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,
               sjlabelled,haven,stringr,ordinal,texreg)  
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2

df1$idunique <- 1:dim(df1)[[1]]

dfreg <- df1 %>% dplyr::select(idunique,egal2,
  class3,
  homclass,
  Q03pcm,
  edyears,
  female,
  agenum,
  union,
  workst,
  WEIGHT,
  region,
  "gini_disp",
  "gini_mkt",
  d10d1,
  rgdpna,
  oecd,
  country2, country, country3,region,
) %>%
  mutate(logrgdpna = log(rgdpna),
         edyears2 = edyears ^ 2,
         age2 = agenum ^ 2) %>%
  filter(country2 != "SVN") %>%
  na.omit() %>% 
  left_join(df1[,c("idunique","n_high","n_middle","n_low")])



phig<- sjPlot::plot_frq(data = dfreg$n_high,show.prc = F,show.n = F)
pmid<- sjPlot::plot_frq(data = dfreg$n_middle,show.prc = F,show.n = F)
plow<- sjPlot::plot_frq(data = dfreg$n_low,show.prc = F,show.n = F)

cowplot::plot_grid(phig, pmid, plow, labels = NULL, nrow = 3,ncol = 1)

ggsave(plot = last_plot(),filename = "n_status_class.png",device = "png",
       path = here::here("output/images"),width = 0.5,height = 1,units = "cm",scale = 20)
```


# Descriptive x country

```{r redistribution}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,sjmisc,GGally,ggplot2)
load(here::here("input/data/proc/study1.RData"))
df1$country<- as.numeric(df1$country)
df1$country2 <- countrycode::countrycode(sourcevar = df1$country,origin = "iso3n",destination = "country.name")
df1$redistF <- factor(df1$redist,levels = 1:5,labels = sjlabelled::get_labels(df1$redist))

df1 %>%
  group_by(country2, ) %>%
  summarise(redist = mean(redist, na.rm = T)) %>% 
  View()

percentage_data <- df1 %>%
  group_by(country2, redistF) %>%
  summarise(count = n()) %>%
  group_by(country2) %>%
  na.omit() %>% 
  mutate(percentage = count / sum(count)) %>% 
  arrange(country2,redistF,percentage) %>% 
  mutate(pct_lab = paste0(round(percentage*100,1),"%")) %>% 
  mutate(pct_lab=ifelse(!redistF %in% c("Strongly agree"),NA,pct_lab))

order <- 
percentage_data %>% 
  filter(redistF=="Strongly agree") %>% 
  arrange(percentage) %>% 
  dplyr::select(country2)

order$orden <- 1:31
ggplot(percentage_data, aes(x=country2,y=percentage*100,fill=redistF,group=redistF,label = pct_lab))+
  geom_bar(stat = 'identity') +
  # geom_text(position = position_fill(vjust =100)) +
  scale_y_continuous(name=NULL,labels = scales::percent_format(scale = 1),limits = c(0,101), expand = c(0, 0)) +
  scale_x_discrete(limits=order$country2,name=NULL) +  
  scale_fill_ordinal(guide = guide_legend(reverse = TRUE)) +
  theme_classic() +
  ggtitle(label= "Government's responsibility: reduce the differences in income between people with high incomes and those with low incomes.") + 
  theme(legend.position = 'bottom',legend.title = element_blank())  +
  coord_flip()

ggsave(plot = last_plot(),filename = "wredist_cn.png",device = "png",
       path = here::here("output"),width = 2,height = 1,units = "cm",scale = 15)


df1$pi_nteg<- rowMeans(df1[,c("pi_compa","pi_isola","pi_left")],na.rm = T)
resits_count <- df1 %>%
  group_by(country,country2) %>%
  summarise(redist = mean(redist,na.rm = T),
            egal
            homclass = mean(homclass,na.rm = T),
            pi_nteg = mean(pi_nteg,na.rm = T),
            pi_ntegm = median(pi_nteg,na.rm = T)
            ) %>%
  na.omit()

cor(df1[,c("redist","homclass","pi_nteg")],use = "complete.obs")

ggplot(data = resits_count,aes(x = homclass,y = redist,label=country2)) +
  xlab("Class-based homogeneity") +
  ylab("Redistributive preferences")+  
  labs(alt = "A",caption = "r=0.42") +  
  geom_smooth(method = "lm") +
  geom_text() 

myorder <-  resits_count$country2[order(resits_count$homclass)]
ggplot(data = resits_count,aes(x =country2,y = homclass)) + 
  geom_segment(aes(x=country2, xend=country2, y=0, yend=homclass), color="black") +
  geom_point() +
  scale_x_discrete(limits=myorder) +
  ylab("Class-based homogeneity")+
  xlab("") +
  theme(axis.text.x = element_text(angle = 45))

ggsave(plot = last_plot(),filename = "homclass_cn.png",device = "png",
       path = here::here("output"),width = 1,height = 1,units = "cm",scale = 20)

myorder <-  resits_count$country2[order(resits_count$pi_nteg)]
ggplot(data = resits_count,aes(x =country2,y = pi_nteg)) + 
  geom_segment(aes(x=country2, xend=country2, y=0, yend=pi_nteg), color="black") +
  geom_point() +
  scale_x_discrete(limits=myorder) +
  ylab("Perceived isolation")+
  xlab("") +
  theme(axis.text.x = element_text(angle = 45))

ggsave(plot = last_plot(),filename = "p_isolat_cn.png",device = "png",
       path = here::here("output"),width = 1,height = 1,units = "cm",scale = 20)
```

```{r redist-homclass-class-country}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,
               sjlabelled,haven,stringr,ordinal,texreg)  
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2

df1$idunique <- 1:dim(df1)[[1]]

dfreg <- df1 %>% dplyr::select(idunique,egal2,
  class3,
  homclass,
  Q03pcm,
  edyears,
  female,
  agenum,
  union,
  workst,
  WEIGHT,
  region,
  "gini_disp",
  "gini_mkt",
  d10d1,
  rgdpna,
  oecd,
  country2, country, country3,region,
) %>%
  mutate(logrgdpna = log(rgdpna),
         edyears2 = edyears ^ 2,
         age2 = agenum ^ 2) %>%
  filter(country2 != "SVN") %>%
  na.omit()

df1[,c("n_high","n_middle","n_low")]

df_mean <- 
dfreg %>% 
  group_by(country3) %>% 
  summarise(egal2_c=mean(egal2),homclass_c=mean(homclass),gini_mkt=mean(gini_mkt),gini_disp=mean(gini_disp))

df_region <- 
dfreg %>% 
  group_by(region,country3) %>% 
  summarise(n())

df_full <- 
dfreg %>% 
  group_by(class3) %>% 
  summarise(egal2=mean(egal2),homclass=mean(homclass),homclass_c=0.3910297,egal2_c=68.81757, country3="All")

df_plot <- 
dfreg %>% 
  group_by(country3,class3) %>% 
  summarise(egal2=mean(egal2),homclass=mean(homclass)) %>% 
  left_join(df_mean) %>%
  left_join(df_region) %>% 
  arrange(gini_mkt)
df_plot <- 
df_plot %>% 
  bind_rows(df_full)

df_plot$class3 <- factor(df_plot$class3,levels = levels(df_plot$class3),labels = c("Service Class (I+II)","Intermediate Class (III+IV+V)","Working Class (VI+VII)"))

table(df_plot$class3)

df_plot %>% 
ggplot()+
  geom_point(aes(x = reorder(country3, egal2_c),y = egal2,shape=class3,color=class3)) +
  geom_hline(yintercept = 68.81757,linetype=2)+ 
  geom_point(aes(x = reorder(country3, egal2_c),y = egal2_c),alpha=1,shape=4) +
  scale_shape_manual(values = c(6, 15, 16)) +
  scale_color_manual(values = c("blue", "#E7B800", "red")) +
  labs(title = "Redistributive preferences and social class by country",x=NULL,y="Redistributive Preferences") +
  theme(legend.position = "bottom",
        axis.text.x=element_text(angle=45,hjust = 1),
        legend.title = element_blank()) 

ggsave(plot = last_plot(),filename = "macro_class_redist.png",device = "png",
       path = here::here("output/images"),width = 1.5,height = 0.9,units = "cm",scale = 16)

df_plot %>% 
ggplot()+
  geom_point(aes(x = reorder(country3, homclass_c),y = homclass,shape=class3,color=class3)) +
  geom_hline(yintercept = 0.3910297,linetype=2)+ 
  geom_point(aes(x = reorder(country3, homclass_c),y = homclass_c),alpha=1,shape=4) +
  scale_shape_manual(values = c(6, 15, 16)) +
  scale_color_manual(values = c("blue", "#E7B800", "red")) +
  labs(title = "Class-based network homogeneity and social class by country",x=NULL,y="Class-based network homogeneity ") +
  theme(legend.position = "bottom",
        axis.text.x=element_text(angle=45,hjust = 1),
        legend.title = element_blank()) 

ggsave(plot = last_plot(),filename = "macro_class_homclass.png",device = "png",
       path = here::here("output/images"),width = 1.5,height = 0.9,units = "cm",scale = 16)

```

# macro correlations

```{r}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,
               sjlabelled,haven,stringr,ordinal,texreg)  
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(
  egal2,
  class3,
  homclass,
  Q03pcm,
  edyears,
  female,
  agenum,
  union,
  workst,
  WEIGHT,
  region,
  "gini_disp",
  "gini_mkt",
  d10d1,
  rgdpna,
  oecd,
  country2, country
) %>%
  mutate(logrgdpna = log(rgdpna),
         edyears2 = edyears ^ 2,
         age2 = agenum ^ 2) %>%
  filter(country2 != "SVN") %>%
  na.omit()

df2$country2 <- countrycode::countrycode(sourcevar = df2$country,origin = "iso3n",destination = "country.name")
df2$country3 <- countrycode::countrycode(sourcevar = df2$country,origin = "iso3n",destination = "iso3c")
df2 <- bind_cols(df2,sjmisc::to_dummy(x = df2$class3,suffix = "numeric"))

macro_data <- df2 %>%
  group_by(country2,country3) %>%
  summarise_at(c("egal2","homclass","pi_isola","tr_courts","tr_inte","gini_disp","gini_mkt",
                 "class3_1","class3_2","class3_3","gv_spen"), mean, na.rm = TRUE) %>% 
  as.data.frame()

macro_data %>%  
ggplot(aes(y=egal2, x=homclass)) +
  # geom_point() +
  geom_text(label=as.character(macro_data$country3)) +
  # scale_x_continuous(limits = c(0,1))+
  # scale_y_continuous(limits = c(1,5))+
  geom_smooth(method = "lm",fullrange=TRUE) +
  xlab("Class homogeneity")+
  ylab("Redistributive preferences") +
  labs(title = "Redistributive preferences and Class homogeneity",
       caption =paste("r=",round(cor(macro_data$homclass,
                                     macro_data$egal2, use='complete.obs'),digits = 2)))

ggsave(plot = last_plot(),filename = "macro_homo_egal.png",device = "png",
       path = here::here("output/images"),width = 1,height = 1,units = "cm",scale = 20)

macro_data %>%  
ggplot(aes(y=homclass, x=class3_3)) +
  # geom_point() +
  geom_text(label=as.character(macro_data$country3)) +
  # scale_x_continuous(limits = c(0,1))+
  # scale_y_continuous(limits = c(1,5))+
  geom_smooth(method = "lm",fullrange=TRUE) +
  xlab("Working class (%)")+
  ylab("Class homogeneity") +
  labs(title = "Class homogeneity and Working class (%)",
       caption =paste("r=",round(cor(macro_data$homclass,
                                     macro_data$class3_3),digits = 2)))

ggsave(plot = last_plot(),filename = "macro_working_homo.png",device = "png",
       path = here::here("output/images"),width = 1,height = 1,units = "cm",scale = 20)

macro_data %>%  
ggplot(aes(y=homclass, x=class3_2)) +
  # geom_point() +
  geom_text(label=as.character(macro_data$country3)) +
  # scale_x_continuous(limits = c(0,1))+
  # scale_y_continuous(limits = c(1,5))+
  geom_smooth(method = "lm",fullrange=TRUE) +
  xlab("Intermediate Class (%)")+
  ylab("Class homogeneity") +
  labs(title = "Class homogeneity and Intermediate Class (%)",
       caption =paste("r=",round(cor(macro_data$homclass,
                                     macro_data$class3_2),digits = 2)))

ggsave(plot = last_plot(),filename = "macro_middle_homo.png",device = "png",
       path = here::here("output/images"),width = 1,height = 1,units = "cm",scale = 20)

macro_data %>%  
ggplot(aes(y=homclass, x=class3_1)) +
  # geom_point() +
  geom_text(label=as.character(macro_data$country3)) +
  # scale_x_continuous(limits = c(0,1))+
  # scale_y_continuous(limits = c(1,5))+
  geom_smooth(method = "lm",fullrange=TRUE) +
  xlab("Service class (%)")+
  ylab("Class homogeneity") +
  labs(title = "Class homogeneity and Service class (%)",
       caption =paste("r=",round(cor(macro_data$homclass,
                                     macro_data$class3_1),digits = 2)))

ggsave(plot = last_plot(),filename = "macro_service_homo.png",device = "png",
       path = here::here("output/images"),width = 1,height = 1,units = "cm",scale = 20)


macro_data %>%  
ggplot(aes(y=homclass, x=gini_disp)) +
  # geom_point() +
  geom_text(label=as.character(macro_data$country3)) +
  # scale_x_continuous(limits = c(0,1))+
  # scale_y_continuous(limits = c(1,5))+
  geom_smooth(method = "lm",fullrange=TRUE) +
  xlab("Gini (Disposable)")+
  ylab("Class homogeneity") +
  labs(title = "Class homogeneity and Gini (Disposable)",
       caption =paste("r=",round(cor(macro_data$homclass,
                                     macro_data$gini_disp),digits = 2)))

ggsave(plot = last_plot(),filename = "macro_giniD_homo.png",device = "png",
       path = here::here("output/images"),width = 1,height = 1,units = "cm",scale = 20)


macro_data %>%  
ggplot(aes(y=homclass, x=gini_mkt)) +
  # geom_point() +
  geom_text(label=as.character(macro_data$country3)) +
  # scale_x_continuous(limits = c(0,1))+
  # scale_y_continuous(limits = c(1,5))+
  geom_smooth(method = "lm",fullrange=TRUE) +
  xlab("Gini (Market)")+
  ylab("Class homogeneity") +
  labs(title = "Class homogeneity and Gini (Market)",
       caption =paste("r=",round(cor(macro_data$homclass,
                                     macro_data$gini_mkt),digits = 2)))

ggsave(plot = last_plot(),filename = "macro_giniM_homo.png",device = "png",
       path = here::here("output/images"),width = 1,height = 1,units = "cm",scale = 20)

```

# Check on homogeneity

- checking how different the measures for homogeneity are.
- the original one is the best one

```{r check-homogeneity}
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,haven,sjmisc,GGally,ggplot2)
load(here::here("input/data/proc/study1_country.RData"))

test <- df2
frq(df2$class11d)
test$egp3_v1 <- car::recode(test$class11d,"1:2=1;c(3,4,5,6)=2;7:10=3",as.factor = T,levels = c(1,2,3))
test$egp3_v2 <- car::recode(test$digclass11d,"1:2=1;c(3,4,5,6)=2;7:10=3",as.factor = T,levels = c(1,2,3))

# I   II IIIa IIIb  IVa  IVb  IVc    V   VI VIIa VIIb 
#   1    2    3    4    5    6    7    8    9   10   11 
frq(df2$dclass11d)
test$egp3_v3 <- car::recode(test$dclass11d,"1:2=1;c(3,4,5,6,7,8)=2;9:11=3",as.factor = T,levels = c(1,2,3))
test$egp3_v4 <- car::recode(test$dclass11d,"1:2=1;c(3,5,6,7,8)=2;c(4,9,10,11)=3",as.factor = T,levels = c(1,2,3))

# Service class II to middle class
test$egp3_v5 <- car::recode(test$dclass11d,"1=1;c(2,3,5,6,7,8)=2;c(4,9,10,11)=3",as.factor = T,levels = c(1,2,3))


frq(test$egp3_v1)
frq(test$egp3_v2)
frq(test$egp3_v3)
frq(test$egp3_v4)
frq(test$egp3_v5)
frq(test$class3)

test$ingroup1 <- NA 
test$ingroup1 <- ifelse(test$egp3_v1==1,test$n_high,test$ingroup1)
test$ingroup1 <- ifelse(test$egp3_v1==2,test$n_middle,test$ingroup1)
test$ingroup1 <- ifelse(test$egp3_v1==3,test$n_low,test$ingroup1)

test$ingroup2 <- NA 
test$ingroup2 <- ifelse(test$egp3_v2==1,test$n_high,test$ingroup2)
test$ingroup2 <- ifelse(test$egp3_v2==2,test$n_middle,test$ingroup2)
test$ingroup2 <- ifelse(test$egp3_v2==3,test$n_low,test$ingroup2)

test$ingroup3 <- NA 
test$ingroup3 <- ifelse(test$egp3_v3==1,test$n_high,test$ingroup3)
test$ingroup3 <- ifelse(test$egp3_v3==2,test$n_middle,test$ingroup3)
test$ingroup3 <- ifelse(test$egp3_v3==3,test$n_low,test$ingroup3)

#ingroup with Routine non-manual IIIa as middle class and IIIb as working class
test$ingroup4 <- NA 
test$ingroup4 <- ifelse(test$egp3_v4==1,test$n_high,test$ingroup4)
test$ingroup4 <- ifelse(test$egp3_v4==2,test$n_middle,test$ingroup4)
test$ingroup4 <- ifelse(test$egp3_v4==3,test$n_low,test$ingroup4)


#ingroup with Service II + Routine non-manual IIIa as middle class and IIIb as working class
test$ingroup5 <- NA 
test$ingroup5 <- ifelse(test$egp3_v5==1,test$n_high,test$ingroup4)
test$ingroup5 <- ifelse(test$egp3_v5==2,test$n_middle,test$ingroup4)
test$ingroup5 <- ifelse(test$egp3_v5==3,test$n_low,test$ingroup4)

test$homclass_v1 <- as.numeric(test$ingroup1/test$know_total)
test$homclass_v2 <- as.numeric(test$ingroup2/test$know_total)
test$homclass_v3 <- as.numeric(test$ingroup3/test$know_total)
test$homclass_v4 <- as.numeric(test$ingroup4/test$know_total)
test$homclass_v5 <- as.numeric(test$ingroup5/test$know_total)

sjPlot::plot_frq(test$homclass_v1,type = "bar")
sjPlot::plot_frq(test$homclass_v2)
sjPlot::plot_frq(test$homclass_v3,type = "bar")
sjPlot::plot_frq(test$homclass_v4,type = "bar")
sjPlot::plot_frq(test$homclass_v5,type = "bar")

hist.default(df2$homclass)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal,texreg)  
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- test %>% dplyr::select(redist,
                        class3,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

hist.default(dfreg$homclass,main = "Class-based network homogeneity",xlab = NULL)

# Models 
base <- lmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,rob1,int_homo)

knitreg(list(homclass,full1,rob1,int_homo))
```


