---
title: "Complementary analysis"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: show  
    number_sections: yes
editor_options: 
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      echo = TRUE 
                      )
options(scipen=9999) # desactivar notacion cientifica
if (!require("pacman")) install.packages("pacman") # instalar pacman
pacman::p_load(dplyr,sjmisc,sjPlot,sjlabelled,tidyverse,haven,MLMusingR)
```


# Individual-level

```{r, results='asis'}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal,texreg,MLMusingR,lme4)  
# rm(list=ls())

load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(
  prefineq,redist,
  egal = egal2,
  dclass3res_V,
  n_middle,n_low,n_high,
  homclass3_V_res,
  know_total,
  Q03pcm,
  edyears,
  female,
  agenum,
  partner,
  workst, 
  WEIGHT,
  region,
  "gini_disp"=wid_gini_disp,
  "gini_mkt",
  gv_spen,
  rel_red,
  d10d1=wid_p90p10,
  wid_p90p50,
  top10=wid_sharetop10,
  rgdpna,
  gdppercapita,
  oecd,
  country2, country, country3,
) %>%
  mutate(logrgdpna = log(rgdpna),
         loggdppercapita=log(gdppercapita),
         edyears2 = edyears ^ 2,
         age2 = agenum ^ 2) %>%
  filter(country2 != "SVN") 

dfreg <- na.omit(dfreg)

## Model -  EGP3 - DIGCLASS - V to Working -----------------------------$

digclas1_VW_7 <- lmer(egal~1 + dclass3res_V+n_low+female+agenum+partner+workst+ (1|country2),data=dfreg,weights = WEIGHT)

digclas1_VW_8 <- lmer(egal~1 + dclass3res_V+n_low+n_middle+female+agenum+partner+workst+ (1|country2),data=dfreg,weights = WEIGHT)

digclas1_VW_10 <- lmer(egal~1 + dclass3res_V+n_low+n_middle+n_high+female+agenum+partner+workst+ (1|country2),data=dfreg,weights = WEIGHT)


digclas1_VW_10.1 <- lmer(egal~1 + dclass3res_V*n_low+n_middle+n_high+female+agenum+partner+workst+ (1|country2),data=dfreg,weights = WEIGHT)

digclas1_VW_10.2 <- lmer(egal~1 + dclass3res_V*n_middle+n_high+n_low+female+agenum+partner+workst+ (1|country2),data=dfreg,weights = WEIGHT)

digclas1_VW_10.3 <- lmer(egal~1 + dclass3res_V*n_high+n_low+n_middle+female+agenum+partner+workst+ (1|country2),data=dfreg,weights = WEIGHT)

digclas1_VW_11 <- lmer(egal~1 + dclass3res_V*n_low + dclass3res_V*n_middle + dclass3res_V*n_high +female+agenum+partner+workst+ (1|country2),data=dfreg,weights = WEIGHT)

digclas1_VW <- list(digclas1_VW_7,digclas1_VW_8,digclas1_VW_10,
                    digclas1_VW_10.1,digclas1_VW_10.2,digclas1_VW_10.3,
                    digclas1_VW_11)

ccoef <- list(homclass3_V_res="Class-based network homogeneity",
              know_total="Network size",
              "dclass3res_VIntermediate class (III+IV)"="Intermediate Class",
              "dclass3res_VWorking Class (V+VI+VII)"="Working Class",
              "n_low" = "Tie to working class",
              "n_middle" = "Tie to Intermediate class",
              "n_high" = "Tie to Service class",
              "dclass3res_VIntermediate class (III+IV):n_low" = "Intermediate x Tie to Working class",
              "dclass3res_VWorking Class (V+VI+VII):n_low"    = "Working x Tie to Working class",
              "dclass3res_VIntermediate class (III+IV):n_middle" = "Intermediate x Tie to Intermediate class",
              "dclass3res_VWorking Class (V+VI+VII):n_middle" = "Working x Tie to Intermediate class",
              "dclass3res_VIntermediate class (III+IV):n_high" = "Intermediate x Tie to Service class",
              "dclass3res_VWorking Class (V+VI+VII):n_high"= "Working x Tie to Service class"
              )

htmlreg(digclas1_VW,stars = c(0.001, 0.01, 0.05, 0.1),single.row = F,symbol = ".",
       file = "output/tables/tableSX.html",
       caption = paste("Table SX: Multilevel models for class-based profiles, social classs and redistributive preferences"),
       custom.note = "Note: Standard errors in parentheses. %stars",
       threeparttable = T,
       caption.above = T,leading.zero = T,
       custom.coef.map = ccoef,
      groups = list("Social Class (Ref.= Service Class)" = 1:2,
                    "Network class-profile" = 3:5,
                    "Interactions Class x Class-profile" = 6:11),
      # custom.gof.rows = list("Controls"=c("Yes",rep("Yes",1))),
      include.loglik = FALSE,
      include.aic = FALSE,
      custom.gof.names = c(NA,NA,"Num. groups","Var: Country (Intercept)","Var: Residual")
      )
```

# Country-level

```{r data-prep}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))

if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal,texreg,MLMusingR,lme4)  
# rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
data_corruption <- xlsx::read.xlsx("input/data/original/coruption-data/CPI2017_Full_DataSet-1801.xlsx",sheetIndex = 1)
data_corruption$year <- 2017
data_unionden <- haven::read_dta("input/data/original/union-density/union-density.dta") 
data_migration <- data.table::fread("input/data/original/migration/migrant-stock-share.csv")
data_unemployment <- data.table::fread("input/data/original/unemployment-world-bank/unemployment-rate.csv")
data_qog <- haven::read_dta("input/data/original/QOG/qog_std_ts_jan25.dta") 
data_vdem <- haven::read_dta("input/data/original/QOG/V-Dem-CY-Full+Others-v15.dta") 

union_den <- 
data_unionden %>% 
  dplyr::select(country=ref_area_label,year=time,union_den=obs_value) %>% 
  mutate(ccode=countrycode::countrycode(country,origin = "country.name",destination = "iso3n"),
         country=countrycode::countrycode(ccode,origin = "iso3n",destination = "country.name"),
         year=as.numeric(year)) 

migration<- 
data_migration %>% dplyr::select(country=Entity,year=Year,mig_share=`Share of the population that was born in another country`) %>% 
  mutate(ccode=countrycode::countrycode(country,origin = "country.name",destination = "iso3n"),
         country=countrycode::countrycode(ccode,origin = "iso3n",destination = "country.name"),
         year=as.numeric(year)) 

corruption <- 
data_corruption %>% 
  dplyr::select(country=Country,year,iso3=ISO3,cpi=CPI.Score.2017) %>% 
  mutate(ccode=countrycode::countrycode(country,origin = "country.name",destination = "iso3n"),
         country=countrycode::countrycode(ccode,origin = "iso3n",destination = "country.name"),
         year=as.numeric(year)) 

unemployment <- 
data_unemployment %>% 
  dplyr::select(country=Entity,year=Year,unemployment_rate=`Unemployment, total (% of total labor force) (modeled ILO estimate)`) %>% 
  mutate(ccode=countrycode::countrycode(country,origin = "country.name",destination = "iso3n"),
         country=countrycode::countrycode(ccode,origin = "iso3n",destination = "country.name"),
         year=as.numeric(year)) 

democracy <- 
data_qog %>% 
  dplyr::select(country=cname,year=year,van_index,p_polity2,fe_etfra) %>% 
  mutate(ccode=countrycode::countrycode(country,origin = "country.name",destination = "iso3n"),
         country=countrycode::countrycode(ccode,origin = "iso3n",destination = "country.name"),
         year=as.numeric(year)) 

vdem <- 
data_vdem %>% 
  dplyr::select(country=country_name,year=year,v2x_delibdem,v2x_polyarchy,v2x_egal,v2catrauni) %>% 
  mutate(ccode=countrycode::countrycode(country,origin = "country.name",destination = "iso3n"),
         country=countrycode::countrycode(ccode,origin = "iso3n",destination = "country.name"),
         year=as.numeric(year)) 

additional_macro <- 
union_den %>% 
  full_join(migration,by=c("ccode","country","year")) %>% 
  full_join(corruption,by=c("ccode","country","year")) %>% 
  full_join(unemployment,by=c("ccode","country","year")) %>%   
  full_join(democracy,by=c("ccode","country","year")) %>%
  full_join(vdem,by=c("ccode","country","year")) %>%  
  arrange(year)

summary(additional_macro)

country_code<- as.numeric(levels(as.factor(as.character(df1$ccode))))


additional_macro_2000to2018 <- 
  additional_macro %>% 
  filter(year %in% c(2015:2017)) %>% 
  filter(ccode %in% country_code)


additional_macro_avg <- 
additional_macro_2000to2018 %>% 
  group_by(ccode) %>% 
  summarise(union_den=mean(union_den,na.rm=T),
            mig_share=mean(mig_share,na.rm=T),
            cpi=mean(cpi,na.rm=T),
            unemployment_rate=mean(unemployment_rate,na.rm=T),
            van_index=mean(van_index,na.rm=T),
            p_polity2=mean(p_polity2,na.rm=T),            
            v2x_delibdem=mean(v2x_delibdem ,na.rm=T),
            v2x_polyarchy=mean(v2x_polyarchy ,na.rm=T),
            v2x_egal = mean(v2x_egal,na.rm=T),
            fe_etfra = mean(fe_etfra,na.rm=T),
            v2catrauni = mean(v2catrauni,na.rm=T)
            )
summary(additional_macro_avg)
save(additional_macro_avg,file ="input/data/proc/additional_macro_avg.RData")
```

```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal,texreg,MLMusingR,lme4)  
# rm(list=ls()) 

load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
load(file ="input/data/proc/additional_macro_avg.RData")

df1$idnum <- rownames(df1)

dfid <- df1 %>% dplyr::select(
  idnum,
  redist,prefineq,
  egal = egal2,
  dclass3res_V,
  homclass3_V_res,
  know_total,
  Q03pcm,
  edyears,
  female,
  agenum,
  partner,
  workst,
  WEIGHT,
  region,
  "gini_disp"=wid_gini_disp,
  "gini_mkt",
  gv_spen,
  rel_red,
  abs_red,
  ilo_taxrev,
  ilo_govspe,
  d10d1=wid_p90p10,
  wid_p90p50,
  top10=wid_sharetop10,
  rgdpna,
  gdppercapita,
  country2, country, country3,
) %>% na.omit()

# Merge new macro-data
df1 <- df1 %>% left_join(.,additional_macro_avg,by ="ccode")
dfreg <- df1 %>% dplyr::select(
  idnum,
  redist,prefineq,
  egal = egal2,
  dclass3res_V,
  homclass3_V_res,
  know_total,
  Q03pcm,
  edyears,
  female,
  agenum,
  partner,
  workst,
  WEIGHT,
  region,
  "gini_disp"=wid_gini_disp,
  "gini_mkt",
  gv_spen,
  rel_red,
  abs_red,
  ilo_taxrev,
  ilo_govspe,
  d10d1=wid_p90p10,
  wid_p90p50,
  top10=wid_sharetop10,
  rgdpna,
  gdppercapita,
  cpi,
  mig_share,
  union_den,
  v2x_polyarchy,
  unemployment_rate,
  v2catrauni,
  country2, country, country3,
) %>%
  filter(country2 != "SVN") %>% 
  # na.omit() %>%
    mutate(loggdppercapita=scale(gdppercapita/1000),
         edyears2 = edyears ^ 2,
         age2 = agenum ^ 2, 
         gini_disp=scale(gini_disp)) %>% 
  filter(idnum %in%  dfid$idnum)

dfreg$wstate2 <- scale(scale(dfreg$abs_red) + scale(dfreg$ilo_taxrev) + scale(dfreg$ilo_govspe))

# Variable Group-Centering ------------------------------------------------$
dfreg <- 
  dfreg %>% 
  mutate(to_dummy(female),
         to_dummy(workst),
         to_dummy(Q03pcm)
         )
dfreg$female_gc = group_center(dfreg$female_2, grp = dfreg$country2)
dfreg$workst_gc = group_center(dfreg$workst_2, grp = dfreg$country2)
dfreg$edyears_gc = group_center(dfreg$edyears, grp = dfreg$country2)
dfreg$agenum_gc = group_center(dfreg$agenum, grp = dfreg$country2)
dfreg$age2_gc = group_center(dfreg$age2, grp = dfreg$country2)
dfreg$homclass3_V_gc <-group_center(dfreg$homclass3_V_res, grp = dfreg$country2)
dfreg$know_total_gc = group_center(dfreg$know_total, grp = dfreg$country2)
dfreg$partner_gc = group_center(as.numeric(dfreg$partner), grp = dfreg$country2)

# Household Income Tercile
dfreg$Q03pcm_1_gc = group_center(dfreg$Q03pcm_1, grp = dfreg$country2)
dfreg$Q03pcm_2_gc = group_center(dfreg$Q03pcm_2, grp = dfreg$country2)
dfreg$Q03pcm_3_gc = group_center(dfreg$Q03pcm_3, grp = dfreg$country2)
dfreg$Q03pcm_NA_gc = group_center(dfreg$Q03pcm_4, grp = dfreg$country2)

# drop dummies
dfreg <- dplyr::select(dfreg,-c(female_1,female_2,
                                workst_2,Q03pcm_1,Q03pcm_2,Q03pcm_2,Q03pcm_4,
                                ))

## Model -  EGP3 - DIGCLASS - V to Working -----------------------------$
homo_V_gini_gdp_wstate2 <- 
  lmer(egal~ 
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2+
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

homo_V_gini_gdp_cpi <-
  lmer(egal~
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2 + cpi +
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

homo_V_gini_gdp_mig <-
  lmer(egal~
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2 + mig_share +
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

homo_V_gini_gdp_union <-
  lmer(egal~
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2 +union_den + 
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

homo_V_gini_gdp_unempl <-
  lmer(egal~
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2 +unemployment_rate + 
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

homo_V_gini_gdp_v2x_polyarchy <-
  lmer(egal~
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2 + v2x_polyarchy +
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

homo_V_gini_full2 <- 
  lmer(egal~ 
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+         
         workst_gc+
         gini_disp +loggdppercapita + wstate2+
         homclass3_V_gc*
         dclass3res_V*
         gini_disp + 
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

homo_V_gini_full3 <- 
  lmer(egal~ 
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2+
         homclass3_V_gc*
         dclass3res_V*
         gini_disp + mig_share + union_den +unemployment_rate + v2x_polyarchy + cpi+ 
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)

models_macro <- list(homo_V_gini_gdp_wstate2,
                     homo_V_gini_gdp_cpi,
                     homo_V_gini_gdp_mig,
                     homo_V_gini_gdp_union,
                     homo_V_gini_gdp_unempl,
                     homo_V_gini_gdp_v2x_polyarchy,
                     homo_V_gini_full2,
                     homo_V_gini_full3
                     )

screenreg(models_macro)

ccoef <- list(homclass3_V_gc="Class-based network homogeneity (CWC)",
              "dclass3res_VIntermediate class (III+IV)"="Intermediate Class",
              "dclass3res_VWorking Class (V+VI+VII)"="Working Class",
              "gini_disp" = "Income inequality (Gini index)",
              loggdppercapita = "GDP/capita",
              wstate2="Size of the welfare state",
              cpi = "Corruption Index",
              mig_share = "Migration (pop %)",
              union_den = "Union density",
              unemployment_rate = "Unemployment rate",
              v2x_polyarchy = "Democracy (polyarchy index)",
              "homclass3_V_gc:dclass3res_VIntermediate class (III+IV)" = "Homogeneity*Intermediate Class",
              "homclass3_V_gc:dclass3res_VWorking Class (V+VI+VII)" = "Homogeneity*Working Class",
              "homclass3_V_gc:gini_disp"= "Homogeneity x Income Inequality",
              "homclass3_V_gc:dclass3res_VIntermediate class (III+IV):gini_disp" = "Homogeneity*Intermediate Class*Income Inequality",
              "homclass3_V_gc:dclass3res_VWorking Class (V+VI+VII):gini_disp" = "Homogeneity*Working Class*Income Inequality")

htmlreg(models_macro,stars = c(0.001, 0.01, 0.05, 0.1),scalebox = 0.7,symbol = ".",
       file = "output/tables/tableSXX.html",
       caption = paste("Table SX: Robustness analysis of the multilevel models for income inequality, network homogeneity and redistributive preferences"),
       custom.note = " Note: All individual level controls centered within cluster (group mean).  Standard errors in parentheses. %stars",
       caption.above = T,leading.zero = T,single.row = F,threeparttable = T,
       custom.coef.map = ccoef,
      # groups = list("Social Class (Ref.= Service Class)" = 2:3,"Homogeneity x Social Class"=7:8),
      # custom.gof.rows = list("Controls"=rep("Yes",4)),
      include.loglik = FALSE,include.aic = FALSE,
      custom.gof.names = c(NA,NA,"Num. groups",
                           "Var: Country (Intercept)",
                           "Var: Country Homogeneity",
                           "Var: Country Intermediate Class ",
                           "Var: Country Working Class",
                           "Cov: Country (Intercept), Homogeneity",
                           "Cov: Country (Intercept), Intermediate Class ",
                           "Cov: Country (Intercept), Working Class",
                           "Cov: Country Homogeneity, Intermediate Class",
                           "Cov: Country Homogeneity, Working Class",
                           "Cov: Country Intermediate Class, Working Class",
                           "Var: Residual")
      )

```

```{r}
homo_V_wstate_full2 <- 
  lmer(egal~ 
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+         
         workst_gc+
         gini_disp +loggdppercapita + wstate2+
         homclass3_V_gc*
         dclass3res_V*
         wstate2 + 
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)


homo_V_gini_wstate <- 
  lmer(egal~ 
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+         
         workst_gc+
         gini_disp +loggdppercapita + wstate2+
         homclass3_V_gc*dclass3res_V*gini_disp + 
         homclass3_V_gc*dclass3res_V*wstate2 + 
         (homclass3_V_gc+dclass3res_V|country2),data=dfreg,weights = WEIGHT)


models_interactions<- list(homo_V_gini_full2,
               homo_V_wstate_full2,
               homo_V_gini_wstate)


ccoef <- list(homclass3_V_gc="Class-based network homogeneity (CWC)",
              "dclass3res_VIntermediate class (III+IV)"="Intermediate Class",
              "dclass3res_VWorking Class (V+VI+VII)"="Working Class",
              "gini_disp" = "Income inequality (Gini index)",
              loggdppercapita = "GDP/capita",
              wstate2="Size of the welfare state",
              "homclass3_V_gc:dclass3res_VIntermediate class (III+IV)" = "Homogeneity*Intermediate Class",
              "homclass3_V_gc:dclass3res_VWorking Class (V+VI+VII)" = "Homogeneity*Working Class",
              "homclass3_V_gc:gini_disp"= "Homogeneity x Income Inequality",
              "homclass3_V_gc:dclass3res_VIntermediate class (III+IV):gini_disp" = "Homogeneity*Intermediate Class*Income Inequality",
              "homclass3_V_gc:dclass3res_VWorking Class (V+VI+VII):gini_disp" = "Homogeneity*Working Class*Income Inequality",
              "homclass3_V_gc:dclass3res_VIntermediate class (III+IV)" = "Homogeneity*Intermediate Class",
              "homclass3_V_gc:dclass3res_VWorking Class (V+VI+VII)" = "Homogeneity*Working Class",
              "homclass3_V_gc:wstate2"= "Homogeneity x Welfare State",
              "homclass3_V_gc:dclass3res_VIntermediate class (III+IV):wstate2" = "Homogeneity*Intermediate Class*Welfare State",
              "homclass3_V_gc:dclass3res_VWorking Class (V+VI+VII):wstate2" = "Homogeneity*Working Class*Welfare State")

htmlreg(models_interactions,stars = c(0.001, 0.01, 0.05, 0.1),scalebox = 0.7,symbol = ".",
       file = "output/tables/tableSXXX.html",
       caption = paste("Table SX: Robustness analysis of the multilevel models for income inequality, network homogeneity and redistributive preferences"),
       custom.note = " Note: All individual level controls centered within cluster (group mean).  Standard errors in parentheses. %stars",
       caption.above = T,leading.zero = T,single.row = F,threeparttable = T,
       custom.coef.map = ccoef,
      # groups = list("Social Class (Ref.= Service Class)" = 2:3,"Homogeneity x Social Class"=7:8),
      # custom.gof.rows = list("Controls"=rep("Yes",4)),
      include.loglik = FALSE,include.aic = FALSE,
      custom.gof.names = c(NA,NA,"Num. groups",
                           "Var: Country (Intercept)",
                           "Var: Country Homogeneity",
                           "Var: Country Intermediate Class ",
                           "Var: Country Working Class",
                           "Cov: Country (Intercept), Homogeneity",
                           "Cov: Country (Intercept), Intermediate Class ",
                           "Cov: Country (Intercept), Working Class",
                           "Cov: Country Homogeneity, Intermediate Class",
                           "Cov: Country Homogeneity, Working Class",
                           "Cov: Country Intermediate Class, Working Class",
                           "Var: Residual")
      )
```

# Power analysis 

```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text=ggplot2::element_text(size=15,  family="serif"))
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal,texreg,MLMusingR,lme4)  
# rm(list=ls()) 

load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
load(file ="input/data/proc/additional_macro_avg.RData")

df1$idnum <- rownames(df1)

dfid <- df1 %>% dplyr::select(
  idnum,
  redist,prefineq,
  egal = egal2,
  dclass3res_V,
  homclass3_V_res,
  know_total,
  Q03pcm,
  edyears,
  female,
  agenum,
  partner,
  workst,
  WEIGHT,
  region,
  "gini_disp"=wid_gini_disp,
  "gini_mkt",
  gv_spen,
  rel_red,
  abs_red,
  ilo_taxrev,
  ilo_govspe,
  d10d1=wid_p90p10,
  wid_p90p50,
  top10=wid_sharetop10,
  rgdpna,
  gdppercapita,
  country2, country, country3,
) %>% na.omit()

# Merge new macro-data
df1 <- df1 %>% left_join(.,additional_macro_avg,by ="ccode")
dfreg <- df1 %>% dplyr::select(
  idnum,
  redist,prefineq,
  egal = egal2,
  dclass3res_V,
  homclass3_V_res,
  know_total,
  Q03pcm,
  edyears,
  female,
  agenum,
  partner,
  workst,
  WEIGHT,
  region,
  "gini_disp"=wid_gini_disp,
  "gini_mkt",
  gv_spen,
  rel_red,
  abs_red,
  ilo_taxrev,
  ilo_govspe,
  d10d1=wid_p90p10,
  wid_p90p50,
  top10=wid_sharetop10,
  rgdpna,
  gdppercapita,
  cpi,
  mig_share,
  union_den,
  v2x_polyarchy,
  unemployment_rate,
  v2catrauni,
  country2, country, country3,
) %>%
  filter(country2 != "SVN") %>% 
  # na.omit() %>%
    mutate(loggdppercapita=scale(gdppercapita/1000),
         edyears2 = edyears ^ 2,
         age2 = agenum ^ 2, 
         gini_disp=scale(gini_disp)) %>% 
  filter(idnum %in%  dfid$idnum)

dfreg$wstate2 <- scale(scale(dfreg$abs_red) + scale(dfreg$ilo_taxrev) + scale(dfreg$ilo_govspe))

library(simr)

homo_V_gini_gdp_wstate2 <- 
  lmer(egal~ 
         gini_disp +
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         gini_disp +loggdppercapita + wstate2+
         (1|country2),data=dfreg,weights = WEIGHT)

coef<- summary(homo_V_gini_gdp_wstate2)$coef[,"Estimate"]
fixed<- as.numeric(coef)
varcomp<- as.data.frame(lme4::VarCorr(homo_V_gini_gdp_wstate2))
varcomp$vcov[1] # var country
varcomp$sdcor[2] # var individual

# fixed intercept and slope
fixed <- fixed
# random intercept and slope variance-covariance matrix
# For class
rand <- varcomp$vcov[1]

# Exrtact the residual sd
s <- varcomp$sdcor[2] 

model <- makeLmer(egal~
         gini_disp +            
         homclass3_V_gc+
         know_total_gc+
         dclass3res_V+
         female_gc+agenum_gc+
         partner_gc+
         edyears_gc+Q03pcm_2_gc+Q03pcm_3_gc+Q03pcm_NA_gc+
         workst_gc+
         loggdppercapita + wstate2+ (1|country2), fixef=fixed, VarCorr=rand, sigma=s, data=dfreg)
model


# For a range of effects sizes 2.2, + 1SD, +2SD, -1SD, -2 SD 


model_ext_country <- extend(model, along = "country2", n =200)

p_sim_gini_disp <- 
powerSim(model_ext_country, 
         test=fixed("gini_disp",method = c("t")),
         # along="country2",
         # breaks = c(10,20,30,40,50,60,70,90,100),
         nsim=1,
         alpha=.05,
         progress=TRUE);p_sim_gini_disp



p_curve_gini_disp <- powerCurve(model_ext_country, 
                            test=fixed("gini_disp",method = c("t")), 
                            along="country2",
                            breaks = c(10,20,30,40,50,60,70,90,100),
                            nsim=5*60,
                            alpha=.05,
                            progress=TRUE)
```


- determine effect sizes (small, medium, high)
- determine number of clusters
- Simulate with 1000, 5000 and 10.000 reps


