---
title: "Estimations plots"
subtitle: "Full sample"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  bookdown::html_document2: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
options(scipen=9999) # desactivar notacion cientifica
```

```{r}
set1 <-  RColorBrewer::brewer.pal(n = 8, name = "Set1")
options(ggplot2.discrete.fill = set1)
options(ggplot2.discrete.colour = set1)
ggplot2::theme_set(theme_minimal())
ggplot2::theme_update(text=element_text(size=15,  family="serif"))  
```

# Preferences for Goverment redistribution

```{r full-redist-est}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,texreg,broom.mixed,ggplot2,haven)  
rm(list=ls())

load(here::here("output/fullsample-numeric-homclass-full-individual.RData")); fsample_num_full_ind<- models
load(here::here("output/fullsample-numeric-homclass-strong-individual.RData"));fsample_num_strong_ind<- models
load(here::here("output/fullsample-numeric-homclass-weak-individual.RData")); fsample_num_weak_ind<- models

coef <- c("homclass","class3Intermediate class (III+IV)","class3Working Class (V+VI+VII)")

df_p_full<- 
bind_rows(
  fsample_num_full_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Full network"),
  fsample_num_strong_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Strong ties"),
  fsample_num_weak_ind[[3]] %>%
    broom.mixed::tidy(conf.int = T) %>%
    filter(term %in% coef) %>%
    mutate(group ="Weak ties")
)
df_p_full$depvar <- "Full sample"
```

```{r nonconfusian-redist-est}
load(here::here("output/nonconfusian-numeric-homclass-full-individual.RData")); nconf_num_full_ind<- models
load(here::here("output/nonconfusian-numeric-homclass-strong-individual.RData"));nconf_num_strong_ind<- models
load(here::here("output/nonconfusian-numeric-homclass-weak-individual.RData")); nconf_num_weak_ind<- models

coef <- c("homclass","class3Intermediate class (III+IV)","class3Working Class (V+VI+VII)")

df_p_nconf<- 
bind_rows(
  nconf_num_full_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Full network"),
  nconf_num_strong_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Strong ties"),
  nconf_num_weak_ind[[3]] %>%
    broom.mixed::tidy(conf.int = T) %>%
    filter(term %in% coef) %>%
    mutate(group ="Weak ties")
)
df_p_nconf$depvar <- "Non-Confusian"
```

```{r oecd-redist-est}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,texreg)  
load(here::here("output/ocde-numeric-homclass-full-individual.RData")); ocde_num_full_ind<- models
load(here::here("output/ocde-numeric-homclass-strong-individual.RData"));ocde_num_strong_ind<- models
load(here::here("output/ocde-numeric-homclass-weak-individual.RData")); ocde_num_weak_ind<- models

df_p_ocde<- 
bind_rows(
  ocde_num_full_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Full network"),
  ocde_num_strong_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Strong ties"),
  ocde_num_weak_ind[[3]] %>%
    broom.mixed::tidy(conf.int = T) %>%
    filter(term %in% coef) %>%
    mutate(group ="Weak ties")
)
df_p_ocde$depvar <- "OECD"
```

```{r coefplot-redist}
df_p<- bind_rows(df_p_full,df_p_nconf,df_p_ocde)
df_p$term <- 
  factor(df_p$term,
         levels = c("class3Working Class (V+VI+VII)",
                    "class3Intermediate class (III+IV)",
                    "homclass"))
df_p$group <- factor(df_p$group,levels = c("Weak ties","Strong ties","Full network"))

ggplot(df_p,
       aes(x = estimate, y = term, color = group)) +
  geom_vline(xintercept = 0) +
  geom_errorbar(
    aes(xmin = conf.low, xmax = conf.high),
    size = 1,
    width = 0.2,
    position = position_dodge(0.5)
  ) +
  geom_point(
    shape = 21,
    size = 3,
    fill = "white",
    position = position_dodge(0.5)
  ) +
  facet_grid(~depvar)+
  scale_y_discrete(
    labels = c(
      "Working Class (VI+VII)",
      "Intermediate class (III+IV+V)",
      "Class-based homogeneity"
    )
  )+
  scale_color_discrete(guide = guide_legend(reverse = TRUE))+
  labs(
    # caption = paste0("N=", nobs(int_homo), ", Countries=", lme4::ngrps(int_homo)),
    color = "Model",
    x="Coefficients (fixed effects)",y=NULL,
    title = "Preferences for Goverment redistribution") +
  theme(axis.text.y.left = element_text(face = "plain", size = 12))
ggsave(plot = last_plot(),filename = "coefplot-redist.png",device = "png",
       path = here::here("output/images"),width = 2,height = 1,units = "cm",scale = 15)
```

# Egalitarian economic preferences 

```{r full-redist-est}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,texreg,broom.mixed,ggplot2,haven)  
rm(list=ls())

load(here::here("output/fullsample-egalitarian-homclass-full-individual.RData")); fsample_egal_full_ind<- models
load(here::here("output/fullsample-egalitarian-homclass-strong-individual.RData"));fsample_egal_strong_ind<- models
load(here::here("output/fullsample-egalitarian-homclass-weak-individual.RData")); fsample_egal_weak_ind<- models

coef <- c("homclass","class3Intermediate class (III+IV)","class3Working Class (V+VI+VII)")


df_p_full<- 
bind_rows(
  fsample_egal_full_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Full network"),
  fsample_egal_strong_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Strong ties"),
  fsample_egal_weak_ind[[3]] %>%
    broom.mixed::tidy(conf.int = T) %>%
    filter(term %in% coef) %>%
    mutate(group ="Weak ties")
)
df_p_full$depvar <- "Full sample"


```

```{r nonconfusian-redist-est}
load(here::here("output/nonconfusian-egalitarian-homclass-full-individual.RData")); nconf_egal_full_ind<- models
load(here::here("output/nonconfusian-egalitarian-homclass-strong-individual.RData"));nconf_egal_strong_ind<- models
load(here::here("output/nonconfusian-egalitarian-homclass-weak-individual.RData")); nconf_egal_weak_ind<- models

coef <- c("homclass","class3Intermediate class (III+IV)","class3Working Class (V+VI+VII)")

df_p_nconf<- 
bind_rows(
  nconf_egal_full_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Full network"),
  nconf_egal_strong_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Strong ties"),
  nconf_egal_weak_ind[[3]] %>%
    broom.mixed::tidy(conf.int = T) %>%
    filter(term %in% coef) %>%
    mutate(group ="Weak ties")
)
df_p_nconf$depvar <- "Non-Confusian"
```

```{r oecd-redist-est}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,texreg)  
load(here::here("output/ocde-egalitarian-homclass-full-individual.RData")); ocde_egal_full_ind<- models
load(here::here("output/ocde-egalitarian-homclass-strong-individual.RData"));ocde_egal_strong_ind<- models
load(here::here("output/ocde-egalitarian-homclass-weak-individual.RData")); ocde_egal_weak_ind<- models

df_p_ocde<- 
bind_rows(
  ocde_egal_full_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Full network"),
  ocde_egal_strong_ind[[3]] %>% 
    broom.mixed::tidy(conf.int = T) %>% 
    filter(term %in% coef) %>% 
    mutate(group ="Strong ties"),
  ocde_egal_weak_ind[[3]] %>%
    broom.mixed::tidy(conf.int = T) %>%
    filter(term %in% coef) %>%
    mutate(group ="Weak ties")
)
df_p_ocde$depvar <- "OECD"
```

```{r coefplot-egal}
df_p<- bind_rows(df_p_full,df_p_nconf,df_p_ocde)
df_p$term <- 
  factor(df_p$term,
         levels = c("class3Working Class (V+VI+VII)",
                    "class3Intermediate class (III+IV)",
                    "homclass"))
df_p$group <- factor(df_p$group,levels = c("Weak ties","Strong ties","Full network"))

ggplot(df_p,
       aes(x = estimate, y = term, color = group)) +
  geom_vline(xintercept = 0) +
  geom_errorbar(
    aes(xmin = conf.low, xmax = conf.high),
    size = 1,
    width = 0.2,
    position = position_dodge(0.5)
  ) +
  geom_point(
    shape = 21,
    size = 3,
    fill = "white",
    position = position_dodge(0.5)
  ) +
  facet_grid(~depvar)+
  scale_y_discrete(
    labels = c(
      "Working Class (VI+VII)",
      "Intermediate class (III+IV+V)",
      "Class-based homogeneity"
    )
  )+
  scale_color_discrete(guide = guide_legend(reverse = TRUE))+
  labs(
    # caption = paste0("N=", nobs(int_homo), ", Countries=", lme4::ngrps(int_homo)),
    color = "Model",
    x="Coefficients (fixed effects)",y=NULL,
    title = "Redistributive Preferences (Index)") +
  theme(axis.text.y.left = element_text(face = "plain", size = 12))

ggsave(plot = last_plot(),filename = "coefplot-egal.png",device = "png",
       path = here::here("output/images"),width = 2,height = 1,units = "cm",scale = 15)

```

```{r coef-egal-fullsample}
ggplot(df_p %>% filter(depvar=="Full sample"),
       aes(x = estimate, y = term, color = group)) +
  geom_vline(xintercept = 0) +
  geom_errorbar(
    aes(xmin = conf.low, xmax = conf.high),
    size = 1,
    width = 0.2,
    position = position_dodge(0.5)
  ) +
  geom_point(
    shape = 21,
    size = 3,
    fill = "white",
    position = position_dodge(0.5)
  ) +
  facet_grid(~depvar)+
  scale_y_discrete(
    labels = c(
      "Working Class (VI+VII)",
      "Intermediate class (III+IV+V)",
      "Class-based homogeneity"
    )
  )+
  scale_color_discrete(guide = guide_legend(reverse = TRUE))+
  labs(
    # caption = paste0("N=", nobs(int_homo), ", Countries=", lme4::ngrps(int_homo)),
    color = "Model",
    x="Coefficients (fixed effects)",y=NULL,
    title = "Redistributive Preferences (Index)") +
  theme(axis.text.y.left = element_text(face = "plain", size = 12))
ggsave(plot = last_plot(),filename = "coefplot-egal-fullsample.png",device = "png",
       path = here::here("output/images"),width = 1.5,height = 1,units = "cm",scale = 15)

```

```{r inter-egal-fnet-fsample}
int_homo <- fsample_egal_full_ind[[4]]
interplot <- 
interplot::interplot(m = int_homo,var1 = "homclass",var2="class3")
df_int <- interplot$data
df_int <- df_int[c(1,2,4),]
df_int$value <- c("Service Class (I+II)","Intermediate class (III+IV+V)","Working Class (VI+VII)")
df_int$value <- factor(df_int$value,ordered = T,
                       levels = c("Working Class (VI+VII)","Intermediate class (III+IV+V)","Service Class (I+II)")) 

df_int %>% 
ggplot() +
  geom_point(aes(x = value,y = coef1)) + 
  geom_errorbar(aes(x = value, ymin = lb, ymax = ub),color="black",width=0.1,size=1) +
  labs(caption = paste0("N=",nobs(int_homo),", Countries=",lme4::ngrps(int_homo))) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10))+
  ylab("Class-based homogeneity (Full ties)")+
  xlab("Social Class")+
  ggtitle("Redistributive preferences") +
  geom_hline(yintercept = 0) + 
  labs(caption = paste0("N=",nobs(int_homo),", Countries=",lme4::ngrps(int_homo))) +    
  theme(plot.title = element_text(size = 15))

ggsave(plot = last_plot(),filename = "mar_homo_class.png",device = "png",
       path = here::here("output/images"),width = 1.5,height = 1,units = "cm",scale = 15)


df_pred1 <- plot_predictions(int_homo, condition = c("homclass","class3"),draw = F) 
# names(df_pred1)
df_pred1 %>% 
ggplot(aes(y =estimate,x=homclass, fill=class3, color=class3,ymin=conf.low, ymax=conf.high)) +
  geom_line(size=0.75) +
  geom_point(size=1) +
  geom_ribbon(alpha=0.2,size=0.5,linetype=1) +
  facet_grid(~factor(class3, levels=
                       c("Working Class (V+VI+VII)","Intermediate class (III+IV)","Service Class (I+II)"),
                     c("Working Class (VI+VII)","Intermediate class (III+IV+V)","Service Class (I+II)"))) +
  labs(caption = paste0("N=",nobs(int_homo),", Countries=",lme4::ngrps(int_homo))) +
  xlab("Network homogeneity (Full ties)")+
  ylab("Redistributive preferences") +
  theme(legend.position = "none", legend.title = element_blank())

ggsave(plot = last_plot(),filename = "predict-egal-fullsample.png",device = "png",
       path = here::here("output/images"),width = 2,height = 1,units = "cm",scale = 14)
```

```{r inter-macro}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,gridExtra)       
rm(list=ls())
load(here::here("output/fullsample-egalitarian-homclass-full-macro.RData"));fsample_egal_full_mac<- list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,int_gini_wiid,int_theil)



p1<- interplot::interplot(m = fsample_egal_full_mac[[1]],var1 = "homclass",var2="gini_disp",ci = .95)+
  ylab("Class-based homogeneity coefficient")+ xlab("Gini disposable") + 
  geom_point()+ geom_hline(yintercept = 0)

ggsave(plot = last_plot(),filename = "marginal-homoXginiD.png",device = "png",
       path = here::here("output/images"),width = 1.25,height = 1,units = "cm",scale = 14)

p2<- interplot::interplot(m = fsample_egal_full_mac[[2]],var1 = "homclass",var2="gini_mkt") +
  ylab("Class-based homogeneity coefficient")+ xlab("Gini market") +geom_point()+ geom_hline(yintercept = 0)

ggsave(plot = last_plot(),filename = "marginal-homoXginiM.png",device = "png",
       path = here::here("output/images"),width = 1.25,height = 1,units = "cm",scale = 14)
 
# Predicted values 
predval1 <- 
plot_predictions(fsample_egal_full_mac[[1]], condition = list("homclass",gini_disp=range),gray = F) +
  labs(caption = paste0("N=",nobs(giniD_int),", Countries=",lme4::ngrps(giniD_int)),
       colour='Gini (Dis)',fill='Gini (Dis)') +
  xlab("Network homogeneity")+
  ylab("Redistributive preferences") +
  theme(legend.position = "right")

ggsave(plot = last_plot(),filename = "predict-homoXginiD.png",device = "png",
       path = here::here("output/images"),width = 1.25,height = 1,units = "cm",scale = 14)

# Predicted values 
predval2 <- 
plot_predictions(fsample_egal_full_mac[[2]], condition = list("homclass",gini_mkt=range),gray = F) +
  labs(caption = paste0("N=",nobs(giniM_int),", Countries=",lme4::ngrps(giniM_int)),
       colour='Gini (Mkt)',fill='Gini (Mkt)') +
  xlab("Network homogeneity")+
  ylab("Redistributive preferences") +
  theme(legend.position = "right")

ggsave(plot = last_plot(),filename = "predict-homoXginiM.png",device = "png",
       path = here::here("output/images"),width = 1.25,height = 1,units = "cm",scale = 14)

```

