---
title: "Multilevel regression models"
subtitle: "Full sample"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    code_folding: hide
    toc_float: 
      collapsed: true
      smooth_scroll: false
      number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
options(scipen=9999) # desactivar notacion cientifica
```

# Numeric
<!----------------------------------------------------------------------------->

## Full network

```{r mod-homclass-numeric,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- lmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-numeric-homclass-full-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-numeric,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                               class3,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+(1|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
# summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT,family = "binomial")
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-numeric-homclass-full-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-numeric-homclass-full-individual.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-numeric-homclass-full-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```

## Strong ties

```{r mod-homclass-numeric-strong-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3,
                        homclass=homclass_s,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- lmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-numeric-homclass-strong-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-numeric-strong-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3,
                        homclass=homclass_s,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+(1|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-numeric-homclass-strong-macro.RData"),compress = "gzip")
```



```{r}
load(here::here("output/fullsample-numeric-homclass-strong-individual.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-numeric-homclass-strong-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```

## Weak ties

```{r mod-homclass-numeric-strong-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3,
                        homclass=homclass_w,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- lmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-numeric-homclass-weak-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-numeric-strong-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3,
                        homclass=homclass_w,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+(1|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-numeric-homclass-weak-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-numeric-homclass-weak-individual.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-numeric-homclass-weak-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```
## R's class 

```{r mod-homclass-numeric-respondent,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3=class3res,
                        homclass,
                        class3spo,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- lmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst+class3spo)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-numeric-homclass-respondent.RData"),compress = "gzip")
```

```{r mod-intermacro-numeric-respondent,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3=class3res,
                        class3spo,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+class3spo+(1|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-numeric-homclass-respondent-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-numeric-homclass-respondent.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-numeric-homclass-respondent-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```


# Binary logit 
<!----------------------------------------------------------------------------->

## Full network

```{r mod-homclass-binary,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistB <- car::recode(df1$redist,"4:5=1;1:3=0",as.factor = T)
dfreg <- df1 %>% dplyr::select(redist=redistB,
                        class3,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- glmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT,family = "binomial"); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-logit-homclass-full-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-binary,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistB <- car::recode(df1$redist,"4:5=1;1:3=0",as.factor = T)
dfreg <- df1 %>% dplyr::select(redist=redistB,
                        class3,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+(1|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT,family = "binomial")
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT,family = "binomial")
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-logit-homclass-full-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-logit-homclass-full-individual.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-logit-homclass-full-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```

## Strong ties

```{r mod-homclass-binary-strong-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistB <- car::recode(df1$redist,"4:5=1;1:3=0",as.factor = T)
dfreg <- df1 %>% dplyr::select(redist=redistB,
                        class3,
                        homclass=homclass_s,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- glmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT,family = "binomial"); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-logit-homclass-strong-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-binary-strong-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistB <- car::recode(df1$redist,"4:5=1;1:3=0",as.factor = T)
dfreg <- df1 %>% dplyr::select(redist=redistB,
                        class3,
                        homclass=homclass_s,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+(1|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT,family = "binomial")
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT,family = "binomial")
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-logit-homclass-strong-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-logit-homclass-strong-individual.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-logit-homclass-strong-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```

## Weak ties

```{r mod-homclass-binary-weak-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistB <- car::recode(df1$redist,"4:5=1;1:3=0",as.factor = T)
dfreg <- df1 %>% dplyr::select(redist=redistB,
                        class3,
                        homclass=homclass_w,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- glmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT,family = "binomial"); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save( models,file = here::here("output/fullsample-logit-homclass-weak-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-binary-weak-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistB <- car::recode(df1$redist,"4:5=1;1:3=0",as.factor = T)
dfreg <- df1 %>% dplyr::select(redist=redistB,
                        class3,
                        homclass=homclass_w,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+(1|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT,family = "binomial")
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)
# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT,family = "binomial")
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-logit-homclass-weak-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-logit-homclass-weak-individual.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-logit-homclass-weak-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```

## R's class 

```{r mod-homclass-binary-respondent,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3=class3res,
                        homclass=homclass_res,
                        class3spo,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- glmer(redist~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst+class3spo)
rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-binary-homclass-respondent.RData"),compress = "gzip")
```

```{r mod-intermacro-binary-respondent,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
dfreg <- df1 %>% dplyr::select(redist,
                        class3=class3res,
                        class3spo,
                        homclass=homclass_res,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+class3spo+(1|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- glmer(formula(main),data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-binary-homclass-respondent-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-binary-homclass-respondent.RData"))
texreg::knitreg(models)

load(here::here("output/fullsample-binary-homclass-respondent-macro.RData"))
texreg::knitreg(list(giniD_int,giniM_int,int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil))
```


# Ordinal 
<!----------------------------------------------------------------------------->

## Full network 

```{r mod-homclass-ordinal,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,haven,ordinal,brms)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2

df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- clmm(redistOR~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + edyears+ Q03pcm+union+workst)
# rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# Bayesian ordinal logit
# brms::brm()
# base <- brm(redistOR~1 + (1|country2),data=dfreg,family=cumulative("logit"))
# homclass<- update(base, . ~ . +homclass)
# full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
# rob1 <- update(full1, . ~ . + edyears+ Q03pcm+union+workst)
# rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)
models <- list(homclass,full1,rob1,int_homo)
save( models,file = here::here("output/fullsample-ologit-homclass-full-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-ordinal, eval=FALSE, include=FALSE, results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3,
                        homclass,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redistOR~class3+ homclass+ edyears+ Q03pcm+ workst+ union+ female+agenum +age2+ (1|country2)"
base <- clmm(formula(main),data=dfreg,weights = WEIGHT,Hess = T)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
# summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+ homclass+ edyears+ Q03pcm+ workst+ union+ female+agenum +age2+ logrgdpna +(homclass|country2)"
base <- clmm(redistOR,data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )

save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-ologit-homclass-full-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-ologit-homclass-full-individual.RData"))
texreg::knitreg(models)
```


## Strong ties

```{r mod-homclass-ordinal-strong-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,haven,ordinal,brms)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2

df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3,
                        homclass=homclass_s,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

## Models 
base <- clmm(redistOR~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + edyears+ Q03pcm+union+workst)
# rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# Bayesian ordinal logit
# brms::brm()
# base <- brm(redistOR~1 + (1|country2),data=dfreg,family=cumulative("logit"))
# homclass<- update(base, . ~ . +homclass)
# full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
# rob1 <- update(full1, . ~ . + edyears+ Q03pcm+union+workst)
# rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save( models,file = here::here("output/fullsample-ologit-homclass-strong-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-ordinal-strong-ties, eval=FALSE, include=FALSE, results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3,
                        homclass=homclass_s,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redistOR~class3+ homclass+ edyears+ Q03pcm+ workst+ union+ female+agenum +age2+ (1|country2)"
base <- clmm(formula(main),data=dfreg,weights = WEIGHT,Hess = T)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
# summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+ homclass+ edyears+ Q03pcm+ workst+ union+ female+agenum +age2+ logrgdpna +(homclass|country2)"
base <- clmm(redistOR,data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-ologit-homclass-strong-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-ologit-homclass-strong-individual.RData"))
texreg::knitreg(models)
```

## Weak ties

```{r mod-homclass-ordinal-weak-ties,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,haven,ordinal,brms)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2

df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3,
                        homclass=homclass_w,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- clmm(redistOR~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + edyears+ Q03pcm+union+workst)
# rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# Bayesian ordinal logit
# brms::brm()
# base <- brm(redistOR~1 + (1|country2),data=dfreg,family=cumulative("logit"))
# homclass<- update(base, . ~ . +homclass)
# full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
# rob1 <- update(full1, . ~ . + edyears+ Q03pcm+union+workst)
# rob2 <- update(rob1, . ~ . -(1|country2) + (homclass|country2))
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save( models,file = here::here("output/fullsample-ologit-homclass-weak-individual.RData"),compress = "gzip")
```

```{r mod-intermacro-ordinal-weak-ties, eval=FALSE, include=FALSE, results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3,
                        homclass=homclass_w,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redistOR~class3+ homclass+ edyears+ Q03pcm+ workst+ union+ female+agenum +age2+ (1|country2)"
base <- clmm(formula(main),data=dfreg,weights = WEIGHT,Hess = T)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
# summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+ homclass+ edyears+ Q03pcm+ workst+ union+ female+agenum +age2+ logrgdpna +(homclass|country2)"
base <- clmm(redistOR,data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-ologit-homclass-weak-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-ologit-homclass-weak-individual.RData"))
texreg::knitreg(models)
```

## R's class 

```{r mod-homclass-ologit-respondent,results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,marginaleffects,sjlabelled,haven,stringr,ordinal)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3=class3res,
                        homclass=homclass_res,
                        class3spo,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Models 
base <- clmm(redistOR~1 + (1|country2),data=dfreg,weights = WEIGHT); icc1<- performance::icc(base)
homclass<- update(base, . ~ . +homclass)
full1 <- update(homclass, . ~ . + class3+female+agenum+age2)
rob1 <- update(full1, . ~ . + class3+edyears+ Q03pcm+union+workst+class3spo)
# anova(rob1,rob2)
# Interactions segregation x class
int_homo <- update(rob1, . ~ . +class3*homclass)

models <- list(homclass,full1,rob1,int_homo)
save(models,file = here::here("output/fullsample-ologit-homclass-respondent.RData"),compress = "gzip")
```

```{r mod-intermacro-ologit-respondent, eval=FALSE, include=FALSE, results='asis'}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,sjmisc,ggplot2,interplot,sjPlot,sjlabelled,haven,stringr,gridExtra)  
rm(list=ls())
load(here::here("input/data/proc/study1_country.RData"));df1 <- df2
df1$redistOR <- ordered(x = df1$redist)
dfreg <- df1 %>% dplyr::select(redistOR,
                        class3=class3res,
                        class3spo,
                        homclass=homclass_res,
                        Q03pcm,
                        edyears,
                        female,
                        agenum,
                        union,
                        workst,
                        WEIGHT,
                        region,
                        "gini_disp",
                        "gini_mkt",
                        rgdpna,
                        oecd,
                        country2,country,
                        palmaratio,
                        top10,
                        middle50,
                        d10d1,
                        giniindex,
                        ttheilge1
                        ) %>% 
  mutate(logrgdpna=log(rgdpna),
         edyears2=edyears^2,
         age2=agenum^2) %>%
  na.omit()

# Homoclass x Gini--------------------------------------------------------------
main <- "redistOR~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+class3spo+(1|country2)"
base <- clmm(formula(main),data=dfreg,weights = WEIGHT)
giniD_gdp<- update(base, . ~ . +gini_disp+logrgdpna)
giniD_rs <- update(giniD_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniD_gdp,giniD_rs)
giniD_int<- update(giniD_rs, . ~ . + homclass*gini_disp + (homclass|country2))
summary(giniD_int)

giniM_gdp<- update(base, . ~ . +gini_mkt+logrgdpna)
giniM_rs <- update(giniM_gdp, . ~ . - (1|country2) + (homclass|country2))
# anova(giniM_gdp,giniM_rs)
giniM_int <- update(giniM_rs, . ~ . + homclass*gini_mkt + (homclass|country2))
summary(giniM_int)
models <- list(giniD_gdp,giniD_rs,giniD_int,
               giniM_gdp,giniM_rs,giniM_int)

# Homoclass x Other Economic Inequality-----------------------------------------
main <- "redist~class3+homclass+edyears+Q03pcm+workst+union+female+agenum+age2+logrgdpna+(homclass|country2)"
base <- lmer(formula(main),data=dfreg,weights = WEIGHT)
int_palma <- update(base, . ~ . +homclass*palmaratio)
int_pc10  <- update(base, . ~ . +homclass*top10)
int_pc50  <- update(base, . ~ . +homclass*middle50)
int_d10d1 <- update(base, . ~ . +homclass*d10d1)
int_gini_wiid <- update(base, . ~ . +homclass*giniindex)
int_theil  <- update(base, . ~ . +homclass*ttheilge1)

models_m <- list(int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil
                 )
save(giniD_gdp,giniD_rs,giniD_int,
                 giniM_gdp,giniM_rs,giniM_int,
                 int_palma,int_pc10,int_pc50,int_d10d1,
                 int_gini_wiid,int_theil,
     file = here::here("output/fullsample-ologit-homclass-respondent-macro.RData"),compress = "gzip")
```

```{r}
load(here::here("output/fullsample-ologit-homclass-respondent.RData"))
texreg::knitreg(models)
```

# Ologit Stata

See https://ignacioriveros1.github.io/r/2020/03/22/r_and_stata.html 

```{r}
# install.packages('RStata')
library(RStata) 
options("RStata.StataPath" = "C:/Stata15/Stata-64")
options("RStata.StataVersion" = 15)

stata("")


clear all
eret list
estimates use 'C:\Users\jiturra\Documents\documentos-pcloud\rgroups-redist\output\fullsample-ologit-homclass-respondent-macro.est',  number(1)
estimates store model1
estimates use 'C:\Users\jiturra\Documents\documentos-pcloud\rgroups-redist\output\fullsample-ologit-homclass-respondent-macro.est',  number(2)
estimates store model2
estimates use 'C:\Users\jiturra\Documents\documentos-pcloud\rgroups-redist\output\fullsample-ologit-homclass-respondent-macro.est',  number(3)
estimates store model3
estimates use 'C:\Users\jiturra\Documents\documentos-pcloud\rgroups-redist\output\fullsample-ologit-homclass-respondent-macro.est',  number(4)
estimates store model4
estimates use 'C:\Users\jiturra\Documents\documentos-pcloud\rgroups-redist\output\fullsample-ologit-homclass-respondent-macro.est',  number(5)
estimates store model5
estimates use 'C:\Users\jiturra\Documents\documentos-pcloud\rgroups-redist\output\fullsample-ologit-homclass-respondent-macro.est',  number(6)
estimates store model6
estimates use 'C:\Users\jiturra\Documents\documentos-pcloud\rgroups-redist\output\fullsample-ologit-homclass-respondent-macro.est',  number(7)
estimates store model7

esttab model1 model2 model3 model4 model5 model6 model7, drop(logrgdpna 1.class3 2.class3 3.class3 female agenum edyears workst union 1.Q03pcm 2.Q03pcm 3.Q03pcm 4.Q03pcm )


```

