---
title: "Data preparation"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output: 
  html_document: 
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
      number_sections: yes
    code_folding: show  
    number_sections: yes
editor_options: 
  chunk_output_type: console
---

# Setup

```{r setup}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      echo = TRUE 
                      )
options(scipen=9999) # desactivar notacion cientifica
if (!require("pacman")) install.packages("pacman") # instalar pacman
load(here::here("input/data/proc/study1.RData"))
pacman::p_load(dplyr,sjmisc,sjPlot,sjlabelled,tidyverse,haven)
```

# Country level

```{r}
countries <- 
df1 %>% 
  group_by(country) %>% 
  summarise(n=n())
countries$ccode <- as.numeric(countries$country)
countries$countryname <- as_character(countries$country)
```

**World Income Inequality Database (WIID)** 

> UNU-WIDER, World Income Inequality Database (WIID) Companion dataset (wiidcountry and/or wiidglobal). Version 30 June 2022. https://doi.org/10.35188/UNU-WIDER/WIIDcomp-300622

```{r , eval=FALSE, include=FALSE}
wiid_long<- haven::read_dta(here::here("input/data/original/WIID_30JUN2022_0/WIID_30JUN2022_0.dta"))
wiid_long$ccode <- countrycode::countrycode(sourcevar = wiid_long$c3,origin = "iso3c",destination = "iso3n")

wiid_long1 <- 
wiid_long %>% 
  filter(ccode %in% countries$ccode) %>% 
  filter(year==2017)

```

```{r}
wiid <- 
  read.csv(file = here::here("input/data/original/wid-percentiles/wiid-data-2015-2020.csv"),sep = ";")
names(wiid) <- tolower(names(wiid))
names(wiid) <- gsub('\\.', '', names(wiid))
wiid$ccode <- countrycode::countrycode(sourcevar = wiid$iso,origin = "iso3c",destination = "iso3n")

wiid_d10d01 <- 
  read.csv(file = here::here("input/data/original/wid-percentiles/wiid-data-D10D01-ratio.csv"),sep = ";")

names(wiid_d10d01) <- tolower(names(wiid_d10d01))
names(wiid_d10d01) <- gsub('\\.', '', names(wiid_d10d01))
wiid_d10d01$ccode <- countrycode::countrycode(sourcevar = wiid_d10d01$iso,origin = "iso3c",destination = "iso3n")
wiid_d10d01 <- 
  wiid_d10d01 %>%  
  filter(ccode %in% countries$ccode) %>% 
  filter(year==2017) %>% 
  select(ccode,everything(),-iso,-country,-year,-giniindex) 

wiid_2017 <- 
wiid %>% 
  filter(ccode %in% countries$ccode) %>% 
  filter(year==2017) %>% 
  select(ccode,everything(),-iso,-country,-year) %>% 
  left_join(wiid_d10d01,by="ccode")
```



**Solt SWDIID**
```{r Solt}
load(file = here::here("input/data/original/swiid9_5/swiid9_5.rda"))
solt <- 
swiid_summary %>% dplyr::select(country,year,gini_disp,gini_mkt) %>% dplyr::filter(year %in% c(2016))
solt$ccode <- countrycode::countrycode(sourcevar = solt$country,origin = "country.name",destination = "iso3n")
solt$country <- NULL
solt_2017 <-  solt %>% filter(ccode %in% countries$ccode) %>% 
  select(ccode,gini_disp,gini_mkt)
```


**Otero et.al (2023)**

```{r otero23}
otero <- 
  read.csv(file = here::here("input/data/original/otero23.csv"),sep = ";")
otero$ccode <- countrycode::countrycode(sourcevar = otero$iso3n,origin = "iso2c",destination = "iso3n")
otero$gdp <- gsub('\\,', '',otero$gdp) 
otero<- otero %>% select(ccode,gv_spen,individualism,gini,gdp)
```


**GDP: PEN data**
```{r pen-data}
pendata<- haven::read_dta(file = here::here("input/data/original/pen-world/pwt1001.dta"))
pendata$ccode <- countrycode::countrycode(sourcevar = pendata$countrycode,origin = "iso3c",destination = "iso3n")
pen_2017 <- pendata %>% filter(ccode %in% countries$ccode,year %in% 2017) %>% select(ccode,everything(),-country,-countrycode,-currency_unit,-year)
```

```{r merge}
macro_data <- 
  left_join(wiid_2017,solt_2017) %>%
  left_join(pen_2017) %>% 
  left_join(otero)

df1$ccode <- as.numeric(df1$country)
df2 <- left_join(df1,macro_data,by="ccode")
df2 <- 
df2 %>% mutate(country2=countrycode::countrycode(sourcevar = ccode,origin = "iso3n",destination = "iso3c"),
               country3=countrycode::countrycode(sourcevar = ccode,origin = "iso3n",destination = "country.name"),
               region=countrycode::countrycode(sourcevar = ccode,origin = "iso3n",destination = "region23")) %>% 
  select(ccode,country2,country3,everything())
```

```{r save}
save(df2,file = here::here("input/data/proc/study1_country.RData"))
sjPlot::view_df(df2,file =here::here("input/data/proc/codebook-s1.html") )
```
